# =========================
# CONFIGURACIÓN DE VÉRTICES
# =========================
vertex.allow-user-move = true
vertex.radius = 14
vertex.shape = circle
vertex.tooltip = false
vertex.label = true

# =========================
# CONFIGURACIÓN DE ARISTAS
# =========================
edge.tooltip = false
edge.label = false
edge.arrow = true
edge.arrowsize = 4

# =========================
# LAYOUT
# =========================

# Mientras más alto ? más separados
layout.repulsive-force = 45000

# Mientras más bajo ? menos se juntan
layout.attraction-force = 18

# Ajuste fino del layout
layout.attraction-scale = 7